[workspace]
resolver = "2"
members = [
    "crates/study-tts-cli",
    "crates/study-tts-core",
    "crates/study-tts-runtime",
    "crates/study-tts-testkit",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
